package com.pisces312.qrcast

import android.graphics.Bitmap
import android.graphics.Color
import com.google.mlkit.vision.barcode.BarcodeScanner
import com.google.mlkit.vision.barcode.BarcodeScanning
import com.google.mlkit.vision.common.InputImage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.withContext
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Decoder for RGB (color) QR codes generated by qrgb.
 *
 * An RGB QR code is composed of 3 standard mono QR codes (R, G, B channels),
 * overlaid using color encoding:
 *   - BLACK = R-black + G-black + B-black
 *   - RED   = R-black + G-white + B-white
 *   - GREEN = R-white + G-black + B-white
 *   - BLUE  = R-white + G-white + B-black
 *   - YELLOW= R-black + G-black + B-white
 *   - CYAN  = R-white + G-black + B-black
 *   - MAGENTA=R-black + G-white + B-black
 *   - WHITE = R-white + G-white + B-white
 *
 * Decoding steps:
 * 1. Classify each pixel into one of 8 colors
 * 2. Reconstruct 3 mono QR images from color classification
 * 3. Decode each mono QR with ML Kit
 * 4. Concatenate R+G+B data and remove padding
 */
class RgbQrDecoder {

    private val barcodeScanner: BarcodeScanner = BarcodeScanning.getClient()

    companion object {
        // Must match generator_bin2.py constants
        const val BOX_SIZE = 3
        const val BORDER = 4

        // Common QR versions to try for auto-detection
        val COMMON_VERSIONS = listOf(10, 15, 20, 25, 30, 35, 40)

        // Color classification tolerance (Manhattan distance per channel)
        const val COLOR_TOLERANCE = 60

        // Target colors
        private val C_BLACK = Triple(0, 0, 0)
        private val C_WHITE = Triple(255, 255, 255)
        private val C_RED = Triple(255, 0, 0)
        private val C_GREEN = Triple(0, 255, 0)
        private val C_BLUE = Triple(0, 0, 255)
        private val C_YELLOW = Triple(255, 255, 0)
        private val C_CYAN = Triple(0, 255, 255)
        private val C_MAGENTA = Triple(255, 0, 255)
    }

    /**
     * Decode an image that may contain either:
     * - A single RGB QR code (fills the whole image)
     * - A canvas with multiple RGB QR codes arranged in a grid
     *
     * Returns a list of decoded ChunkInfo objects.
     */
    suspend fun decodeImage(bitmap: Bitmap): List<ChunkInfo> = withContext(Dispatchers.Default) {
        // Try single QR first (treat whole image as one QR code)
        val singlePayload = decodeRgbQr(bitmap)
        if (singlePayload != null) {
            val chunk = parsePayloadV2(singlePayload)
            if (chunk != null) {
                LogCollector.i("RgbQrDecoder", "Decoded as single RGB QR, seq=${chunk.seq}")
                return@withContext listOf(chunk)
            }
        }

        // Try canvas mode (auto-detect grid)
        decodeCanvas(bitmap)
    }

    /**
     * Decode a canvas image containing multiple RGB QR codes in a grid.
     * Auto-detects cell_size by trying common QR versions.
     */
    private suspend fun decodeCanvas(bitmap: Bitmap): List<ChunkInfo> {
        val cellSize = detectCellSize(bitmap)
        if (cellSize == null) {
            LogCollector.w("RgbQrDecoder", "Failed to detect QR cell size")
            return emptyList()
        }

        val cols = bitmap.width / cellSize
        val rows = bitmap.height / cellSize
        LogCollector.i("RgbQrDecoder", "Canvas grid: ${cols}x${rows}, cellSize=$cellSize")

        val chunks = mutableListOf<ChunkInfo>()

        for (row in 0 until rows) {
            for (col in 0 until cols) {
                val x = col * cellSize
                val y = row * cellSize

                // Ensure we don't read beyond bitmap bounds
                val w = kotlin.math.min(cellSize, bitmap.width - x)
                val h = kotlin.math.min(cellSize, bitmap.height - y)
                if (w < cellSize || h < cellSize) continue

                val qrBitmap = Bitmap.createBitmap(bitmap, x, y, w, h)
                val payload = decodeRgbQr(qrBitmap)
                qrBitmap.recycle()

                if (payload != null) {
                    val chunk = parsePayloadV2(payload)
                    if (chunk != null) {
                        chunks.add(chunk)
                    }
                }
            }
        }

        LogCollector.i("RgbQrDecoder", "Decoded ${chunks.size} QR codes from canvas")
        return chunks
    }

    /**
     * Auto-detect cell_size by trying to decode the QR at (0,0)
     * with different common QR versions.
     */
    private suspend fun detectCellSize(bitmap: Bitmap): Int? {
        for (version in COMMON_VERSIONS) {
            val cellSize = calculateCellSize(version)
            if (cellSize > bitmap.width || cellSize > bitmap.height) continue

            val qrBitmap = Bitmap.createBitmap(bitmap, 0, 0, cellSize, cellSize)
            val payload = decodeRgbQr(qrBitmap)
            qrBitmap.recycle()

            if (payload != null && isValidPayload(payload)) {
                LogCollector.i("RgbQrDecoder", "Detected QR version $version, cellSize=$cellSize")
                return cellSize
            }
        }
        return null
    }

    /**
     * Decode a single RGB QR code bitmap.
     * Returns the reconstructed payload bytes (padding removed),
     * or null if any channel fails to decode.
     */
    private suspend fun decodeRgbQr(qrBitmap: Bitmap): ByteArray? = coroutineScope {
        val width = qrBitmap.width
        val height = qrBitmap.height

        // Allocate pixel arrays initialized to white
        val rPixels = IntArray(width * height) { Color.WHITE }
        val gPixels = IntArray(width * height) { Color.WHITE }
        val bPixels = IntArray(width * height) { Color.WHITE }

        // Classify each pixel and fill channel arrays
        for (y in 0 until height) {
            for (x in 0 until width) {
                val pixel = qrBitmap.getPixel(x, y)
                val colorClass = classifyColor(pixel)

                val idx = y * width + x
                when (colorClass) {
                    ColorClass.BLACK -> {
                        rPixels[idx] = Color.BLACK
                        gPixels[idx] = Color.BLACK
                        bPixels[idx] = Color.BLACK
                    }
                    ColorClass.RED -> rPixels[idx] = Color.BLACK
                    ColorClass.GREEN -> gPixels[idx] = Color.BLACK
                    ColorClass.BLUE -> bPixels[idx] = Color.BLACK
                    ColorClass.YELLOW -> {
                        rPixels[idx] = Color.BLACK
                        gPixels[idx] = Color.BLACK
                    }
                    ColorClass.CYAN -> {
                        gPixels[idx] = Color.BLACK
                        bPixels[idx] = Color.BLACK
                    }
                    ColorClass.MAGENTA -> {
                        rPixels[idx] = Color.BLACK
                        bPixels[idx] = Color.BLACK
                    }
                    ColorClass.WHITE -> { /* already white */ }
                    ColorClass.UNKNOWN -> {
                        // Fallback threshold
                        val r = (pixel shr 16) and 0xFF
                        val g = (pixel shr 8) and 0xFF
                        val b = pixel and 0xFF
                        if (r < 128) rPixels[idx] = Color.BLACK
                        if (g < 128) gPixels[idx] = Color.BLACK
                        if (b < 128) bPixels[idx] = Color.BLACK
                    }
                }
            }
        }

        // Build channel bitmaps
        val rBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val gBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val bBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)

        rBitmap.setPixels(rPixels, 0, width, 0, 0, width, height)
        gBitmap.setPixels(gPixels, 0, width, 0, 0, width, height)
        bBitmap.setPixels(bPixels, 0, width, 0, 0, width, height)

        // Decode three channels in parallel
        val rDeferred = async { decodeChannel(rBitmap) }
        val gDeferred = async { decodeChannel(gBitmap) }
        val bDeferred = async { decodeChannel(bBitmap) }

        val results = awaitAll(rDeferred, gDeferred, bDeferred)

        // Clean up
        rBitmap.recycle()
        gBitmap.recycle()
        bBitmap.recycle()

        val rData = results[0]
        val gData = results[1]
        val bData = results[2]

        if (rData == null || gData == null || bData == null) {
            return@coroutineScope null
        }

        // Combine channels: R + G + B = padded payload
        val paddedPayload = ByteArray(rData.size + gData.size + bData.size)
        System.arraycopy(rData, 0, paddedPayload, 0, rData.size)
        System.arraycopy(gData, 0, paddedPayload, rData.size, gData.size)
        System.arraycopy(bData, 0, paddedPayload, rData.size + gData.size, bData.size)

        // Remove trailing padding (zero bytes added to make length divisible by 3)
        var actualLen = paddedPayload.size
        while (actualLen > 0 && paddedPayload[actualLen - 1] == 0.toByte()) {
            actualLen--
        }

        if (actualLen <= 0) return@coroutineScope null
        paddedPayload.copyOfRange(0, actualLen)
    }

    /**
     * Decode a single mono QR channel bitmap using ML Kit.
     */
    private suspend fun decodeChannel(bitmap: Bitmap): ByteArray? {
        return try {
            val image = InputImage.fromBitmap(bitmap, 0)
            val barcodes = barcodeScanner.process(image).await()
            barcodes.firstOrNull()?.rawBytes
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Classify a pixel color into one of 8 standard colors + UNKNOWN.
     * Uses Manhattan distance to the nearest target color.
     */
    private fun classifyColor(pixel: Int): ColorClass {
        val r = (pixel shr 16) and 0xFF
        val g = (pixel shr 8) and 0xFF
        val b = pixel and 0xFF

        val candidates = listOf(
            ColorClass.BLACK to C_BLACK,
            ColorClass.WHITE to C_WHITE,
            ColorClass.RED to C_RED,
            ColorClass.GREEN to C_GREEN,
            ColorClass.BLUE to C_BLUE,
            ColorClass.YELLOW to C_YELLOW,
            ColorClass.CYAN to C_CYAN,
            ColorClass.MAGENTA to C_MAGENTA
        )

        var best = ColorClass.WHITE
        var minDist = Int.MAX_VALUE

        for ((cls, target) in candidates) {
            val dist = kotlin.math.abs(r - target.first) +
                    kotlin.math.abs(g - target.second) +
                    kotlin.math.abs(b - target.third)
            if (dist < minDist) {
                minDist = dist
                best = cls
            }
        }

        return if (minDist > COLOR_TOLERANCE * 3) ColorClass.UNKNOWN else best
    }

    private fun calculateCellSize(version: Int): Int {
        return (4 * version + 17 + 2 * BORDER) * BOX_SIZE
    }

    /**
     * Quick validation that payload looks like a v2 chunk.
     */
    private fun isValidPayload(payload: ByteArray): Boolean {
        if (payload.size < 12) return false
        val buffer = ByteBuffer.wrap(payload).order(ByteOrder.BIG_ENDIAN)
        val seq = buffer.int
        val total = buffer.int
        val protoVer = payload[10].toInt() and 0xFF
        return protoVer == 0x02 && seq >= 0 && total > 0 && seq < total
    }

    private enum class ColorClass {
        BLACK, WHITE, RED, GREEN, BLUE, YELLOW, CYAN, MAGENTA, UNKNOWN
    }
}

/**
 * Parse v2 payload bytes into ChunkInfo.
 * Shared between MainActivity (mono QR) and RgbQrDecoder (color QR).
 */
fun parsePayloadV2(raw: ByteArray): ChunkInfo? {
    if (raw.size < 12) return null
    val buffer = ByteBuffer.wrap(raw).order(ByteOrder.BIG_ENDIAN)
    val seq = buffer.int
    val total = buffer.int
    val dataLen = buffer.short.toInt() and 0xFFFF
    val protoVer = buffer.get().toInt() and 0xFF
    val flags = buffer.get().toInt() and 0xFF

    if (protoVer != 0x02) return null
    if (dataLen > raw.size - 12) return null

    val dataSegment = raw.copyOfRange(12, 12 + dataLen)

    var fileName: String? = null
    var fileCrc32: Long? = null
    var fileSize: Long? = null
    var payload = dataSegment

    if (seq == 0) {
        if (dataSegment.isEmpty()) return null
        val fileNameLen = dataSegment[0].toInt() and 0xFF
        if (1 + fileNameLen + 8 > dataSegment.size) return null
        fileName = String(dataSegment, 1, fileNameLen, Charsets.UTF_8)
        val metaBuf = ByteBuffer.wrap(dataSegment, 1 + fileNameLen, 8).order(ByteOrder.BIG_ENDIAN)
        fileCrc32 = metaBuf.int.toLong() and 0xFFFFFFFFL
        fileSize = metaBuf.int.toLong() and 0xFFFFFFFFL
        payload = dataSegment.copyOfRange(1 + fileNameLen + 8, dataSegment.size)
    }

    return ChunkInfo(
        seq = seq,
        total = total,
        payload = payload,
        fileName = fileName,
        fileCrc32 = fileCrc32,
        fileSize = fileSize,
        isCompressed = (flags and 0x01) != 0
    )
}

/**
 * Extension to convert Google Play Services Task to suspend function.
 */
suspend fun <T> com.google.android.gms.tasks.Task<T>.await(): T =
    suspendCancellableCoroutine { cont ->
        addOnSuccessListener { result -> cont.resume(result) }
        addOnFailureListener { e -> cont.resumeWithException(e) }
    }
